sudo: required
services: 
  - docker

before_install:
  - docker build -t shreykejriwal/react-test -f ./client/Dockerfile.dev ./client
scripts:
  docker run -e CI=true shreykejriwal/react-test npm test

after_success:
  - docker build -t shreykejriwal/multi-client ./client
  - docker build -t shreykejriwal/multi-server ./server
  - docker build -t shreykejriwal/multi-nginx ./nginx
  - docker build -t shreykejriwal/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push shreykejriwal/multi-client 
  - docker push shreykejriwal/multi-nginx 
  - docker push shreykejriwal/multi-server 
  - docker push shreykejriwal/multi-worker 